### ISSUE TITLE
Add references and/or links to the technologies

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/choralcloud.github.io#10]
We need to have references as per the ruberic. I am not sure if links to the technologies count, I think we should add them in anyways, but this is entirely up to you.

The essential thing is putting references from the progress reports on the bottom of the page.

**Comment by houtan1** [comment]
From the updated website rubric:
"More than seven citations that are appropriate"

**Comment by houtan1** [comment]
Merged in #15
