### ISSUE TITLE
Remove references to seng499

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/choralcloud.github.io#4]
I think we should pretend we are a startup and not make any mention of the fact that this is a project

**Comment by houtan1** [comment]
I'm trying to find a marking rubric for the website where it dictates whether we should mention the fact that it's a project or not, and I can't find one. Thoughts? @ecuellog

**Comment by andreirtaylor** [comment]
as per the rubric, this is definitely not possible. Closing
